# Generated by Django 4.1.7 on 2023-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("QuestionId", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=200)),
                ("OptionA", models.CharField(max_length=200)),
                ("OptionB", models.CharField(max_length=200)),
                ("OptionC", models.CharField(max_length=200)),
                ("OptionD", models.CharField(max_length=200)),
                ("Answer", models.CharField(max_length=1)),
            ],
        ),
    ]
